controller_list:
  - name: mirabb/abb_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  - name: mirabb/eoat_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - joint8
    - joint9
    - joint10

