controller_list:
  - name: fake_abb_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_eoat_controller
    type: $(arg fake_execution_type)
    joints:
      - joint10
      - joint8
      - joint9
initial:  # Define initial robot poses per group
  - group: abb_arm
    pose: abb_home
  - group: eoat
    pose: eoat_pose1