mirabb/gazebo_ros_control/pid_gains:
  joint1: {p: 1000.0, i: 0, d: 0}
  joint2: {p: 1000.0, i: 0, d: 0}
  joint3: {p: 1000.0, i: 0, d: 0}
  joint4: {p: 1000.0, i: 0, d: 0}
  joint5: {p: 1000.0, i: 0, d: 0}
  joint6: {p: 1000.0, i: 0, d: 0}
  joint8: {p: 1000.0, i: 0, d: 0}
  joint9: {p: 1000.0, i: 0, d: 0}
  joint10: {p: 1000.0, i: 0, d: 0}
  joint11: {p: 1000.0, i: 0, d: 0}
