# parameters for Gazebo ROS control plugin
gazebo_ros_control/pid_gains:

    joint_link0_link1: {p: 100.0, i: 0.01, d: 10.0}
    joint_link1_link2: {p: 100.0, i: 0.01, d: 10.0}
    joint_link2_link3: {p: 100.0, i: 0.01, d: 10.0}
    joint_link3_link4: {p: 100.0, i: 0.01, d: 10.0}
    joint_link4_link5: {p: 100.0, i: 0.01, d: 10.0}
    joint_link5_link6: {p: 100.0, i: 0.01, d: 10.0}
    joint_frame_Lpad: {p: 100.0, i: 0.01, d: 10.0}
    joint_Lpad_lifter: {p: 100.0, i: 0.01, d: 10.0}
    joint_frame_Slifter: {p: 100.0, i: 0.01, d: 10.0}
    joint_Slifter_Spad: {p: 100.0, i: 0.01, d: 10.0}