mirabb:
  #Controller to control robot arm joints
  abb_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [joint1, joint2, joint3, joint4, joint5,joint6]

  #Controller to control end effector joints
  eoat_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [joint8, joint9, joint10]

  #Controller to continuously publish joint states/positions
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50