controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_link0_link1
      - joint_link1_link2
      - joint_link2_link3
      - joint_link3_link4
      - joint_link4_link5
      - joint_link5_link6
  - name: fake_eoat_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_frame_Lpad
      - joint_Lpad_lifter
      - joint_frame_Slifter
      - joint_Slifter_Spad
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: home
  - group: eoat
    pose: pose2