controller_list:
  - name: arm_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_link0_link1
      - joint_link1_link2
      - joint_link2_link3
      - joint_link3_link4
      - joint_link4_link5
      - joint_link5_link6
  - name: eoat_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_frame_Lpad
      - joint_Lpad_lifter
      - joint_frame_Slifter
      - joint_Slifter_Spad
  - name: abbrobot_conytoller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []