mirabb_rev2:
# mirabb_rev2_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


# --------------works------------------------------------ 
  joint_abb_1_to_abb_0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_abb_1_to_abb_0
    pid: {p: 1000.0, i: 1.0, d: 1000.0}

  joint_abb_2_to_abb_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_abb_2_to_abb_1
    pid: {p: 1000.0, i: 1.0, d: 1000.0}

  joint_abb_3_to_abb_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_abb_3_to_abb_2
    pid: {p: 1000.0, i: 1.0, d: 100.0}

  joint_abb_4_to_abb_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_abb_4_to_abb_3
    pid: {p: 1000.0, i: 1.0, d: 1000.0}

  joint_abb_5_to_abb_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_abb_5_to_abb_4
    pid: {p: 1000.0, i: 1.0, d: 1000.0}

  joint_abb_6_to_abb_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_abb_6_to_abb_5
    pid: {p: 1000.0, i: 1.0, d: 1000.0}

# -------------------------------------------------------------

  # joint_abb_1_to_abb_0_position_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joint: joint_abb_1_to_abb_0
  #   pid: {p: 1000.0, i: 1.0, d: 1000.0}

  # joint_abb_2_to_abb_1_position_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joint: joint_abb_2_to_abb_1
  #   pid: {p: 1000.0, i: 1.0, d: 1000.0}

  # joint_abb_3_to_abb_2_position_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joint: joint_abb_3_to_abb_2
  #   pid: {p: 1000.0, i: 1.0, d: 100.0}

  # joint_abb_4_to_abb_3_position_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joint: joint_abb_4_to_abb_3
  #   pid: {p: 1000.0, i: 1.0, d: 1000.0}

  # joint_abb_5_to_abb_4_position_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joint: joint_abb_5_to_abb_4
  #   pid: {p: 1000.0, i: 1.0, d: 1000.0}

  # joint_abb_6_to_abb_5_position_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joint: joint_abb_6_to_abb_5
  #   pid: {p: 1000.0, i: 1.0, d: 1000.0}
    